name: Deployment Setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job-one:
    name: Deploy
    runs-on: windows-latest
    steps:
      - name: Setup Project
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Build
        working-directory: ./glinka-frontend
        run: npm run build
