name: Deploy to VPS

on: push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Build Project
        run: npm run build






